name: Main Code Sanity

on:
  push:
    branches:
      - main
jobs:
  lint-and-tests:
    uses: ./.github/workflows/lint-and-tests.yml

  build:
    runs-on: macos-latest
    needs: [ lint-and-tests ]
    strategy:
      matrix:
        include:
          - platform: android
            command: ":composeApp:assembleRelease"
          - platform: ios
            command: ":composeApp:linkDebugFrameworkIosArm64"
          - platform: jvm
            command: ":composeApp:jvmJar"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build ${{ matrix.platform }} artifacts
        run: ./gradlew ${{ matrix.command }}
