name: CI

on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run ktlint
        run: ./gradlew ktlintCheck

  tests:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - platform: android
            command: ":composeApp:cleanTestProdDebugUnitTest :composeApp:testProdDebugUnitTest"
          - platform: ios
            command: ":composeApp:cleanIosSimulatorArm64Test :composeApp:iosSimulatorArm64Test"
          - platform: jvm
            command: ":composeApp:cleanJvmTest :composeApp:jacocoJvmTestCoverageVerification"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run tests ${{ matrix.platform }}
        run: ./gradlew ${{ matrix.command }}

      - name: Upload JVM coverage report
        if: matrix.platform == 'jvm'
        uses: actions/upload-artifact@v4
        with:
          name: jvm-coverage-report
          path: composeApp/build/reports/jacoco/jvmTestResult

  build:
    runs-on: macos-latest

    strategy:
      matrix:
        include:
          - platform: android
            command: ":composeApp:assembleRelease"
          - platform: ios
            command: ":composeApp:linkDebugFrameworkIosArm64"
          - platform: jvm
            command: ":composeApp:jvmJar"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build ${{ matrix.platform }} artifacts
        run: ./gradlew ${{ matrix.command }}
